name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: nci

      - name: Build
        run: nr build

      - name: Commit files
        run: |
          git config --global user.email "1136843910@qq.com"
          git config --global user.name "Cansiny0320"
          git add dist && echo "Git Added"
          git commit -m 'chore: update dist' && echo "Git Committed"
          git push -u origin master && echo "Git Pushed Origin"
